### ISSUE TITLE
Cannot read properties of undefined (reading 'creator')

### ISSUE THREAD

**Issue by sgurin** [PolymeshAssociation/polymesh-wallet#249]
Hi, guys. Got an error 
![image](https://user-images.githubusercontent.com/25930200/188642245-f966e7ed-6766-4d22-ae9a-b7935c01a410.png)

![image](https://user-images.githubusercontent.com/25930200/188642465-54917ec9-179e-4716-94cd-788b69ab5749.png)

And I think that is the reason why **web3AccountsSubscribe** not working via **@polkadot/extension-dapp** so I cannot handle switching between Networks

Could you please review

**Comment by F-OBrien** [comment]
@sgurin Currently the testnet runtime is on v5.0.2, while mainnet is on v4.1.2. The version of the wallet extension on the chrome store is not fully compatible with v5.0.2, as seen from your error.

This issue will be addressed in the next release. There is a development release of the wallet in the chrome store that will allow you to use testnet without this wallet error. See https://chrome.google.com/webstore/detail/polymesh-wallet/ihppiagplceklfpgloomoiehdjikkacp

**IF YOU DO DECIDE TO USE THE DEVELOPMENT WALLET IT SHOULD ONLY BE USED WITH TESTNET**
**Ensure you disable or remove the mainnet wallet when using the dev wallet to avoid conflicts between the two extensions**

**Comment by sgurin** [comment]
Still the same issue on Development Extension Version
![image](https://user-images.githubusercontent.com/25930200/188691609-be251e9e-3e72-45c4-9018-2252c1173b93.png)
![image](https://user-images.githubusercontent.com/25930200/188691728-92a035a6-883f-4c56-aafe-081b124234fb.png)

**Comment by F-OBrien** [comment]
That's because the development wallet is not compatible with the current mainnet runtime. You need to use development with Testnet and the official release with Mainnet until the runtime on mainnet is update to match testnet at which point the official wallet will also be updated.

**Comment by sgurin** [comment]
Thanks a lot

**Comment by yzrbl** [comment]
Hi there, Robinland dev lead here. We are an unofficial partner of Polymath/Polymesh and a friend of Vincent's, as well as partner of the tech solution team that sgurin@ is a part of. 

Assuming this issue will be fully addressed in the next release, may I ask for a rough ETA of the next release's timeline just so that we can plan our launches better that integrates with the Polymesh SDK? Thank you very much!

**Comment by F-OBrien** [comment]
@yzrbl The mainnet update is on hold pending Ledger approval and release of an update hardware wallet app in Ledger Live. The official release on their end is taking longer than we expected and the latest information is that it still may not be approved this month.

If you've any general questions about integration you can reach out to us on the Polymesh discord server.

**Comment by KisIrene** [comment]
@F-OBrien @yzrbl  Hello guys.  Could you let me know whether this issue with Ledger Live has been resolved and updated?

**Comment by F-OBrien** [comment]
> @F-OBrien @yzrbl Hello guys. Could you let me know whether this issue with Ledger Live has been resolved and updated?

@KisIrene Yes. The Polymesh Ledger app was updated a couple of months ago. it can be downloaded from ledger live. The latest ledger app version is v3.5.000003.0

**Comment by KisIrene** [comment]
Thank you so much!!!
